name: CI/CD Pineline for Auth-service

on: 
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures all branches and tags are fetched
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use the version of Node.js that your project requires
     
      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn build

      # Debugging step to verify build output
      - name: Debug build output
        run: ls -al ./auth-service/build
      # - name: Archive build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build
      #     path: ./auth-service/build

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Node.JS
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"
        
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: build
  #         path: ./build

  #     - name: Prepare Deployment Directories
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.EC2_IP }} # 44.201.60.122
  #         username: ${{ secrets.EC2_USERNAME }} # ubuntu
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         ports: 22
  #         script: |
  #           mkdir -p /home/ubuntu/auth-service/build
  #           mkdir -p /home/ubuntu/auth-service/build/configs

  #     - name: Copy files to EC2
  #       uses: appleboy/scp-action@master
  #       with:
  #         host: ${{ secrets.EC2_IP }}
  #         username: ${{ secrets.EC2_USERNAME }} # Update as per your setup
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         port: 22
  #         source: "./build/*"
  #         target: "/home/ubuntu/auth-service/build"
  #         strip_components: 4